apiVersion: config.kjournal/v1alpha1
kind: APIServerConfig

backend:
  elasticsearch:
    url: 
    - ${ELASTICSEARCH_URI}

apis:
- resource: containerlogs
  fieldMap:
    metadata.namespace: [kubernetes.namespace]
    metadata.creationTimestamp: ["@timestamp"]
    pod: [kubernetes.pod.name]
    container: [kubernetes.container.name]
    payload: ["."]
    metadata.labels: [kubernetes.labels]
    metadata.annotations.host: [kubernetes.node.name]
    metadata.annotations.pod_id: [kubernetes.pod.uid]

  dropFields:
  - payload.@timestamp
  - payload.kubernetes

  backend:
    elasticsearch:
      index: "*"
      timestampFields: ["@timestamp"]

- resource: events
  backend:
    elasticsearch:
      index: "*"
      timestampFields: ["metadata.creationTimestamp"]

- resource: auditevents
  backend:
    elasticsearch:
      index: "*"
      timestampFields: ["stageTimestamp"]

- resource: logs
  fieldMap:
    metadata.creationTimestamp: ["@timestamp", "metadata.creationTimestamp", "stageTimestamp"]
    payload: ["."]
  backend:
    elasticsearch:
      timestampFields: ["@timestamp", "metadata.creationTimestamp", "stageTimestamp"]
      index: "*"