config:
  logLevel: debug
  logFormat: pretty
  receivers:
    - name: "dump"
      elasticsearch:
        hosts:
          - http://elasticsearch-master:9200
        index: k8sevents
        # Ca be used optionally for time based indices, accepts Go time formatting directives
        indexFormat: "k8sevents-{2006-01-02}"
        useEventID: true
        deDot: false
  route:
    routes:
      - match:
          - receiver: "dump"
