apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.core.kjournal
  labels:
    api: kjournal
    apiserver: "true"
spec:
  version: v1alpha1
  group: core.kjournal
  groupPriorityMinimum: 2000
  service:
    name: apiserver
  versionPriority: 10
  insecureSkipTLSVerify: true
