project_name: kjournal

builds:
- id: cli
  dir: cli
  main: ./cmd/
  binary: kjournal-cli
  goos:
  - linux
  - darwin
  - windows    
- id: apiserver
  main: ./cmd
  binary: kjournal-apiserver
  goos:
  - linux
  goarch:
  - amd64
  - arm
  - arm64
  env:
  - CGO_ENABLED=0

archives:
- id: cli
  name_template: "{{ .ProjectName }}_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  builds:
  - cli
- id: apiserver
  name_template: "{{ .ProjectName }}_apiserver_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  builds:
  - apiserver

release:
  extra_files:
  - glob: config/release/*.yaml

checksum:
  extra_files:
  - glob: config/release/*.yaml

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source_code"

changelog:
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Fixes'
      regexp: "^.*fix[(\\ w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

sboms:
- id: source
  artifacts: source
  documents:
  - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

dockers:
- image_templates:
  - ghcr.io/raffis/{{ .ProjectName }}/cli:{{ .Version }}-amd64
  dockerfile: cli/Dockerfile.release
  use: buildx
  ids:
  - cli
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}-cli
  - --label=org.opencontainers.image.description={{ .ProjectName }}-cli
  - --label=org.opencontainers.image.url=https://github.com/raffis/{{ .ProjectName }}-cli
  - --label=org.opencontainers.image.source=https://github.com/raffis/{{ .ProjectName }}-cli
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates: ["ghcr.io/raffis/{{ .ProjectName }}/cli:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: cli/Dockerfile.release
  use: buildx
  ids:
  - cli
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}-cli
  - --label=org.opencontainers.image.description={{ .ProjectName }}-cli
  - --label=org.opencontainers.image.url=https://github.com/raffis/{{ .ProjectName }}-cli
  - --label=org.opencontainers.image.source=https://github.com/raffis/{{ .ProjectName }}-cli
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates:
  - ghcr.io/raffis/{{ .ProjectName }}/apiserver:{{ .Version }}-amd64
  dockerfile: Dockerfile.release
  use: buildx
  ids:
  - apiserver
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}-apiserver
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/raffis/{{ .ProjectName }}-apiserver
  - --label=org.opencontainers.image.source=https://github.com/raffis/{{ .ProjectName }}-apiserver
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates:
  - ghcr.io/raffis/{{ .ProjectName }}/apiserver:{{ .Version }}-arm64v8
  goarch: arm64
  dockerfile: Dockerfile.release
  use: buildx
  ids:
  - apiserver 
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}-apiserver
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/raffis/{{ .ProjectName }}-apiserver
  - --label=org.opencontainers.image.source=https://github.com/raffis/{{ .ProjectName }}-apiserver
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
- name_template: ghcr.io/raffis/{{ .ProjectName }}/cli:{{ .Version }}
  image_templates:
  - ghcr.io/raffis/{{ .ProjectName }}/cli:{{ .Version }}-amd64
  - ghcr.io/raffis/{{ .ProjectName }}/cli:{{ .Version }}-arm64v8
- name_template: ghcr.io/raffis/{{ .ProjectName }}/cli:latest
  image_templates:
  - ghcr.io/raffis/{{ .ProjectName }}/cli:{{ .Version }}-amd64
  - ghcr.io/raffis/{{ .ProjectName }}/cli:{{ .Version }}-arm64v8
- name_template: ghcr.io/raffis/{{ .ProjectName }}/apiserver:{{ .Version }}
  image_templates:
  - ghcr.io/raffis/{{ .ProjectName }}/apiserver:{{ .Version }}-amd64
  - ghcr.io/raffis/{{ .ProjectName }}/apiserver:{{ .Version }}-arm64v8
- name_template: ghcr.io/raffis/{{ .ProjectName }}/apiserver:latest
  image_templates:
  - ghcr.io/raffis/{{ .ProjectName }}/apiserver:{{ .Version }}-amd64
  - ghcr.io/raffis/{{ .ProjectName }}/apiserver:{{ .Version }}-arm64v8

brews:
- ids:
  - cli
  license: "Apache-2.0"
  tap:
    owner: raffis
    name: kjournal
  folder: Formula
  test: |
    system "#{bin}/kjournal help"      
  install: |
    bin.install "kjournal-cli" => "kjournal"
    generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")

signs:
- cmd: cosign
  certificate: "${artifact}.pem"
  env:
  - COSIGN_EXPERIMENTAL=1
  args:
  - sign-blob
  - "--output-certificate=${certificate}"
  - "--output-signature=${signature}"
  - "${artifact}"
  artifacts: checksum
  output: true

docker_signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  artifacts: images
  output: true
  args:
  - 'sign'
  - '${artifact}'
