apiVersion: config.kjournal/v1alpha1
kind: APIServerConfig

backend: 
  elasticsearch:
    url:
    - http://elasticsearch-master:9200

apis:
- resource: containerlogs
  fieldMap:
    metadata.namespace: [kubernetes.namespace_name]
    metadata.creationTimestamp: ["@timestamp"]
    pod: [kubernetes.pod_name]
    container: [kubernetes.container_name]
    payload: ["."]
    metadata.labels: [kubernetes.labels]
    metadata.annotations.docker_id: [kubernetes.docker_id]
    metadata.annotations.host: [kubernetes.host]
    metadata.annotations.pod_id: [kubernetes.pod_id]


  dropFields:
  - payload.@timestamp
  - payload.kubernetes

  backend:
    elasticsearch:
      index: logstash-*

- resource: events
  backend:
    elasticsearch:
        index: k8sevents-*

- resource: auditevents
  backend:
    elasticsearch:
        index: k8saudit-*

- resource: logs
  fieldMap:
    metadata.creationTimestamp: ["@timestamp"]
    payload: ["."]
  backend:
    elasticsearch:
      index: "*"