apiVersion: config.kjournal/v1alpha1
kind: APIServerConfig

backend: 
  elasticsearch:
    url:
    - http://elasticsearch-master:9200

apis:
- resource: containerlogs
  fieldMap:
    metadata.namespace: kubernetes.namespace_name
    metadata.creationTimestamp: "@timestamp"
    metadata.annotations.kjournal/fluentbit-meta: "kubernetes"
    pod: kubernetes.pod_name
    container: kubernetes.container_name
    payload: "."
  backend:
    elasticsearch:
      index: logstash-*

- resource: events
  backend:
    elasticsearch:
        index: k8sevents-*

- resource: auditevents
  backend:
    elasticsearch:
        index: k8saudit-*

- resource: logs
  fieldMap:
    metadata.creationTimestamp: "@timestamp"
    payload: "."
  backend:
    elasticsearch:
        index: "*"