apiVersion: config.kjournal/v1alpha1
kind: APIServerConfig

backends: 
- name: elasticsearch
  type: elasticsearch
  elasticsearch:
    url:
    - http://elasticsearch-master:9200

apis:
- name: containerlogs
  fieldMap:
    metadata.namespace: kubernetes.namespace_name
    metadata.creationTimestamp: "@timestamp"
    metadata.annotations.kjournal/fluentbit-meta: "kubernetes"
    pod: kubernetes.pod_name
    container: kubernetes.container_name
    payload: "."
  backend:
    name: elasticsearch
    elasticsearch:
      index: logstash-*

- name: events
  backend:
    name: elasticsearch
    elasticsearch:
        index: k8sevents-*

- name: auditevents
  fieldMap:
    metadata.creationTimestamp: RequestReceivedTimestamp
  backend:
    name: elasticsearch
    elasticsearch:
        index: k8saudit-*

- name: logs
  fieldMap:
    metadata.creationTimestamp: "@timestamp"
    payload: "."
  backend:
    name: elasticsearch
    elasticsearch:
        index: "*"

  