site_name: kjournal
site_url: https://raffis.githubpages.io/kjournal
site_description: 
copyright: 
repo_name: raffis/kjournal
repo_url: https://github.com/raffis/kjournal
edit_uri: edit/main/docs

theme:
  name: material
  language: en
  logo: static/avatar.png
  favicon: static/favicon.ico
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"  # Light mode
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"  # Dark mode
      scheme: slate
      primary: light blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/goreleaser

nav:
- Home: index.md
- quick-start.md
- how-it-works.md
- Prerequisites:
  - prerequisites/audit.md
  - prerequisites/ship.md
- Server:
  - server/install.md
  - Storage:
    - server/storage/elasticsearch.md
    - server/storage/other.md
  - Command Line Usage:
      - server/cmdref/kjournal-apiserver.md
- CLI:
  - cli/install.md
  - Command Line Usage:
      - cli/cmdref/kjournal.md
      - cli/cmdref/kjournal_audit.md
      - cli/cmdref/kjournal_clusteraudit.md
      - cli/cmdref/kjournal_diary.md
      - cli/cmdref/kjournal_version.md
- Tutorials:
  - tutorials/kind.md
- API:
  - api/container.v1beta1.md
  - api/audit.v1.md
- Community:
  - contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
