apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: apiserver-config
  files:
  - apiserver-config.yaml

patchesStrategicMerge:
- |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: apiserver
  spec:
    template:
      spec:
        containers:
        - name: apiserver
          volumeMounts:
          - mountPath: /config.yaml
            name: apiserver-config
            subPath: apiserver-config.yaml
        volumes:
        - name: apiserver-config
          configMap:
            name: apiserver-config
