# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kjournal < Formula
  desc ""
  homepage ""
  version "0.0.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.7/kjournal_cli_0.0.7_darwin_amd64.tar.gz"
      sha256 "36c627a0e7d427adba2024d22b891f8766e942dabbc39ce2b68f6dace4c994e7"

      def install
        bin.install "kjournal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.7/kjournal_cli_0.0.7_darwin_arm64.tar.gz"
      sha256 "03dba30d7c728610ed618e2f74a9d6efa654333caf9e1b89a3d17132b085cc0a"

      def install
        bin.install "kjournal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.7/kjournal_cli_0.0.7_linux_arm64.tar.gz"
      sha256 "30915472a31d89476a48d919a80e1419e0c1f2ef40ab31ccdeaf3648ff952bb8"

      def install
        bin.install "kjournal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.7/kjournal_cli_0.0.7_linux_amd64.tar.gz"
      sha256 "f04db9e9c73921ef3383c3f45510c9502bd67bbe3e068c97f95caf962c88d704"

      def install
        bin.install "kjournal"
      end
    end
  end

  test do
    system "#{bin}/kjournal help"
  end
end
