# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kjournal < Formula
  desc ""
  homepage ""
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.6/kjournal_cli_0.0.6_darwin_arm64.tar.gz"
      sha256 "cfc45290efbe06f96b11724ae366de19c54b99e9ca1d1cb93c60409705a4816d"

      def install
        bin.install "kjournal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.6/kjournal_cli_0.0.6_darwin_amd64.tar.gz"
      sha256 "ff39a20f40c23ecf603c5f8a8f485cd83ee7e4ddc8f571df865ff23b9c4a53af"

      def install
        bin.install "kjournal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.6/kjournal_cli_0.0.6_linux_arm64.tar.gz"
      sha256 "1cfeae387fca145ed480c2fc12cd341092e9f6cc3cdab91ca6e9bf4eb194c9d5"

      def install
        bin.install "kjournal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.6/kjournal_cli_0.0.6_linux_amd64.tar.gz"
      sha256 "b9f76551213841061beba40aae6d4b99d6d70546308e5cc0fa69a1f821e9a210"

      def install
        bin.install "kjournal"
      end
    end
  end

  test do
    system "#{bin}/kjournal help"
  end
end
