annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 0.11.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: Kubernetes Event Exporter makes it easy to export Kubernetes events to
  other tools, thereby enabling better event observability, custom alerts and aggregation.
home: https://github.com/bitnami/charts/tree/master/bitnami/kubernetes-event-exporter
icon: https://bitnami.com/assets/stacks/kubernetes-event-exporter/img/kubernetes-event-exporter-stack-220x234.png
keywords:
- alerting
- event exporting
- events
- kubernetes events
- monitoring
- observability
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: kubernetes-event-exporter
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/kubernetes-event-exporter
- https://github.com/resmoio/kubernetes-event-exporter
version: 1.5.2
