---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/instance: 
  app.kubernetes.io/version: ""
  app.kubernetes.io/part-of: flux
fieldSpecs:
  - path: metadata/labels
    create: true
