apiVersion: batch/v1
kind: Job
metadata:
  name: log-generator
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: generator
        image: bash
        command:
        - bash
        - -c 
        - |
          echo '{"foobar": "foobar", "message": "dummy log message"}'
      restartPolicy: Never
  backoffLimit: 1