apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
- ../default
patches:
- target:
    kind: Deployment
    name: kjournal-apiserver
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --es-url=http://elasticsearch-master:9200

