package manifestgen

import (
	"fmt"
	"os"
	"path/filepath"

	securejoin "github.com/cyphar/filepath-securejoin"
)

const GenWarning = "# This manifest was generated by kjournal. DO NOT EDIT."

// Manifest holds the data of a multi-doc YAML
type Manifest struct {
	// Relative path to the YAML file
	Path string
	// Content in YAML format
	Content string
}

// WriteFile writes the YAML content to a file inside the the root path.
// If the file does not exist, WriteFile creates it with permissions perm,
// otherwise WriteFile overwrites the file, without changing permissions.
func (m *Manifest) WriteFile(rootDir string) (string, error) {
	output, err := securejoin.SecureJoin(rootDir, m.Path)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(output), os.ModePerm); err != nil {
		return "", fmt.Errorf("unable to create dir, error: %w", err)
	}

	if err := os.WriteFile(output, []byte(m.Content), os.ModePerm); err != nil {
		return "", fmt.Errorf("unable to write file, error: %w", err)
	}
	return output, nil
}
