apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: validation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kjournal-cluster-view
subjects:
  - kind: ServiceAccount
    name: validation
