apiVersion: kjournal.config/v1beta1
backends: 
- name: elasticsearch
  type: elasticsearch
  elasticsearch:
      url: https://localhost:8080
      cacert: true
      dd: d

bindings:
  container: conainer
  audit: audit
  event: event

buckets:
- name: container
  backend:
    name: elasticsearch
    elasticsearch:
        index: logstash-*
  fieldMap:
    metadata.namespace: kubernetes.namespace
    metadata.creationTimestamp: @es_ts
    pod: kubernetes.pod_name
    container: kubernetes.container_name

- name: audit
  backend:
    name: elasticsearch
    elasticsearch:
        index: k8saudit-*

- name: event
  backend:
    name: elasticsearch
    elasticsearch:
        index: event-*

- name: syslog
  backend:
    elasticsearch:
        index: syslog-*
