# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kjournal < Formula
  desc ""
  homepage ""
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.8/kjournal_cli_0.0.8_darwin_arm64.tar.gz"
      sha256 "36a4be60495adfe74367f1bfdf234db080d57bb744f6b5132d1f1bdd15253f66"

      def install
        bin.install "kjournal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.8/kjournal_cli_0.0.8_darwin_amd64.tar.gz"
      sha256 "a96b26a6b7e6f03863ba58b4f1a23bbec559f53cdd8994fdb6a1c81f8e31de5b"

      def install
        bin.install "kjournal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.8/kjournal_cli_0.0.8_linux_arm64.tar.gz"
      sha256 "ef314f776cd01e17534b22b65c0415e1fb226204a2f63b9bee3a3d4dd67edc73"

      def install
        bin.install "kjournal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.8/kjournal_cli_0.0.8_linux_amd64.tar.gz"
      sha256 "4c0d2e3ceb046627c93fe1f787f63766ad273a0e61a538094d0547deea7460fb"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
  end

  test do
    system "#{bin}/kjournal help"
  end
end
