# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kjournal < Formula
  desc ""
  homepage ""
  version "0.0.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.15/kjournal_cli_0.0.15_darwin_amd64.tar.gz"
      sha256 "105ae5d4805de1bf6583f28673f94dc4f20192bd774e12940e89b32cb3bb07a3"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.15/kjournal_cli_0.0.15_darwin_arm64.tar.gz"
      sha256 "1a72e8ab17137e9d04ef9961c75d0141b2e9ef349cf220dd61cc36ab115ce215"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.15/kjournal_cli_0.0.15_linux_arm64.tar.gz"
      sha256 "e546b64f467689ada2c616d74897ee9aa2116600f86a91b24987a8d03a22f022"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.15/kjournal_cli_0.0.15_linux_amd64.tar.gz"
      sha256 "cbbf5ae7adba17cd5bcfc6853e71a8283f452c9aba32e027cd83ce9d88ca607c"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
  end

  test do
    system "#{bin}/kjournal help"
  end
end
