# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kjournal < Formula
  desc ""
  homepage ""
  version "0.0.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.14/kjournal_cli_0.0.14_darwin_amd64.tar.gz"
      sha256 "3ccb649900f21488beaa28ca58daea13f78a89d0d9d40643a799fbe287232f35"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.14/kjournal_cli_0.0.14_darwin_arm64.tar.gz"
      sha256 "6961087855d1dde84552447757dca5ebd3a59d80550968b990d47945fc0dc1e6"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.14/kjournal_cli_0.0.14_linux_arm64.tar.gz"
      sha256 "5f53a94e62f8a323a616f959abedbd352ed9a19e6ddf3ea3232a84e637fa2fc1"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raffis/kjournal/releases/download/v0.0.14/kjournal_cli_0.0.14_linux_amd64.tar.gz"
      sha256 "6513975b512a643a56e81cab2708574d9c21a4505643e03e970fff6f86973aec"

      def install
        bin.install "kjournal-cli" => "kjournal"
        generate_completions_from_executable(bin/"kjournal", "completion", base_name: "kjournal")
      end
    end
  end

  test do
    system "#{bin}/kjournal help"
  end
end
