package main

import (
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var dir string

var cmdMan = &cobra.Command{
	Use:   "cmdman",
	Short: "Generate kjournal command reference",
	RunE: func(cmd *cobra.Command, args []string) error {
		return genCmdMan()
	},
	Hidden: true,
}

func genCmdMan() error {
	// Remove the line 'Auto generated by spf13/cobra on ...'
	rootCmd.DisableAutoGenTag = true
	header := &doc.GenManHeader{Title: "kjournal", Section: "1"}
	return doc.GenManTree(rootCmd, header, dir)
}

func init() {
	cmdMan.Flags().StringVarP(&dir, "directory", "d", "./", "Path to the output directory")
}
