{{- if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1" }}
apiVersion: apiregistration.k8s.io/v1
{{- else }}
apiVersion: apiregistration.k8s.io/v1beta1
{{- end }}
kind: APIService
metadata:
{{- if or .Values.certManager.enabled .Values.customAnnotations }}
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ printf "%s/%s-root-cert" (include "kjournal.namespace" .) (include "kjournal.fullname" .) | quote }}
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-root-cert" (include "kjournal.namespace" .) (include "kjournal.fullname" .) | quote }}
    {{- if .Values.customAnnotations }}
    {{- toYaml .Values.customAnnotations | nindent 4 }}
    {{- end }}
{{- end }}
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
  name: v1.audit.kjournal
spec:
  service:
    name: {{ template "kjournal.fullname" . }}
    namespace: {{ include "kjournal.namespace" . | quote }}
  {{- if .Values.tls.enable }}
  caBundle: {{ b64enc .Values.tls.ca }}
  {{- end }}
  group: audit.kjournal
  version: v1
  insecureSkipTLSVerify: {{ if or .Values.tls.enable .Values.certManager.enabled }}false{{ else }}true{{ end }}
  groupPriorityMinimum: 100
  versionPriority: 100
