{{- if .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "kjournal.fullname" . }}
  namespace: {{ include "kjournal.namespace" . }}
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "kjournal.fullname" . }}
  namespace: {{ include "kjournal.namespace" . }}
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
spec:
  secretName: {{ template "kjournal.fullname" . }}
  duration: {{ .Values.certManager.certDuration }}
  issuerRef:
    kind: Issuer
    name: {{ template "kjournal.fullname" . }}
  dnsNames:
  - {{ template "kjournal.fullname" . }}
  - {{ template "kjournal.fullname" . }}.{{ include "kjournal.namespace" . }}
  - {{ template "kjournal.fullname" . }}.{{ include "kjournal.namespace" . }}.svc
{{- end -}}