apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
  name: {{ template "kjournal.name" . }}-container
rules:
- apiGroups:
  - "container.kjournal"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch
