apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
  name: {{ template "kjournal.fullname" . }}
  namespace: {{ include "kjournal.namespace" . }}
spec:
  replicas: {{ .Values.replicas }}
  strategy: {{ toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "kjournal.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "kjournal.labels" . | indent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
      name: {{ template "kjournal.name" . }}
      annotations:
        checksum/config: {{ include "kjournal.configHash" . }}
        {{- if .Values.customAnnotations }}
        {{- toYaml .Values.customAnnotations | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "kjournal.serviceAccountName" . }}
      {{- if .Values.hostNetwork.enabled }}
      hostNetwork: true
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end}}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.env }}
        env:
        {{- toYaml .Values.env | trim | nindent 8 }}
        {{- end }}
        args:
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        - --secure-port={{ .Values.listenPort }}
        - --cert-dir=/tmp
        {{- if or .Values.tls.enable .Values.certManager.enabled }}
        - --tls-cert-file=/var/run/serving-cert/tls.crt
        - --tls-private-key-file=/var/run/serving-cert/tls.key
        {{- end }}
        {{- if .Values.extraArguments }}
        {{- toYaml .Values.extraArguments | trim | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.listenPort }}
          name: https
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        {{- with .Values.dnsConfig }}
        dnsConfig:
          {{ toYaml . | indent 8 }}
        {{- end }}
        {{- if .Values.securityContext }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.extraVolumeMounts }}
        {{ toYaml .Values.extraVolumeMounts | trim | nindent 10 }}
        {{ end }}
        - mountPath: /config.yaml
          name: apiserver-config
          subPath: apiserver-config.yaml
        - mountPath: /tmp
          name: tmp
        {{- if or .Values.tls.enable .Values.certManager.enabled }}
        - mountPath: /var/run/serving-cert
          name: volume-serving-cert
          readOnly: true
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      volumes:
      {{- if .Values.extraVolumes  }}
      {{ toYaml .Values.extraVolumes | trim | nindent 6 }}
      {{ end }}
      - name: apiserver-config
        configMap:
          {{- $name := include "kjournal.fullname" . }}
          name: {{ default $name .Values.apiserverConfig.existingConfigMap }}
      - name: tmp
        emptyDir: {}
      {{- if or .Values.tls.enable .Values.certManager.enabled }}
      - name: volume-serving-cert
        secret:
          secretName: {{ template "kjournal.fullname" . }}
      {{- end }}
