{{- if .Values.psp.create -}}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "kjournal.fullname" . }}
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
spec:
  {{- if .Values.hostNetwork.enabled }}
  hostNetwork: true
  hostPorts:
    - min: {{ .Values.listenPort }}
      max: {{ .Values.listenPort }}
  {{- end }}
  fsGroup:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAs
    ranges:
    - min: 1024
      max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - emptyDir
  - configMap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
  name: {{ template "kjournal.name" . }}-psp
rules:
- apiGroups: 
  - 'policy'
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "kjournal.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
  name: {{ template "kjournal.name" . }}-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kjournal.name" . }}-psp
subjects:
- kind: ServiceAccount
  name: {{ template "kjournal.serviceAccountName" . }}
  namespace: {{ include "kjournal.namespace" . | quote }}
{{- end -}}
