{{- if .Values.tls.enable -}}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.customAnnotations }}
  annotations:
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
  name: {{ template "kjournal.fullname" . }}
  namespace: {{ include "kjournal.namespace" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc .Values.tls.certificate }}
  tls.key: {{ b64enc .Values.tls.key }}
{{- end -}}
