apiVersion: v1
kind: Service
metadata:
  {{- if or .Values.service.annotations .Values.customAnnotations }}
  annotations:
  {{- if .Values.service.annotations }}
  {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  {{- if .Values.customAnnotations }}
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
  name: {{ template "kjournal.fullname" . }}
  namespace: {{ include "kjournal.namespace" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    {{- include "kjournal.selectorLabels" . | indent 4 }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
