{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kjournal.labels" . | indent 4 }}
  name: {{ template "kjournal.serviceAccountName" . }}
  namespace: {{ include "kjournal.namespace" . }}
{{- if or .Values.serviceAccount.annotations .Values.customAnnotations }}
  annotations:
  {{- if .Values.serviceAccount.annotations }}
  {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.customAnnotations }}
  {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
