{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: {{ template "kjournal.fullname" . }}-view
rules:
- apiGroups:
  - core.kjournal
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
{{- end }}