
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.core.kjournal
  labels:
    api: kjournal
    apiserver: "true"
spec:
  version: v1alpha1
  group: core.kjournal
  groupPriorityMinimum: 2000
  service:
    name: kjournal
    namespace: logging
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4VENDQXEyZ0F3SUJBZ0lVSTlTMmhiY3VIZ3FMSCtOdmVlWFZiZndqblhVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNkVzR4Q3pBSkJnTlZCQWdNQW5OME1Rb3dDQVlEVlFRSERBRnNNUW93Q0FZRApWUVFLREFGdk1Rc3dDUVlEVlFRTERBSnZkVEVuTUNVR0ExVUVBd3dlYTJwdmRYSnVZV3d0WTJWeWRHbG1hV05oCmRHVXRZWFYwYUc5eWFYUjVNQjRYRFRJeU1EY3dOekUxTXpFeE0xb1hEVEl6TURjd056RTFNekV4TTFvd2FERUwKTUFrR0ExVUVCaE1DZFc0eEN6QUpCZ05WQkFnTUFuTjBNUW93Q0FZRFZRUUhEQUZzTVFvd0NBWURWUVFLREFGdgpNUXN3Q1FZRFZRUUxEQUp2ZFRFbk1DVUdBMVVFQXd3ZWEycHZkWEp1WVd3dFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFvaXdzeERkK1E1T0UKYnhYYTA0MWluWnJLRWxGdHdxSjlEM296QnRIc3ptNldFeGdreklNYng3NnF1YnI3ZnBYeUZvV0F0Tk42cy81bAo4Ny9OQWRQMWZHSklFdlp2b0FLOU5sTUNZbUZkc2NDNlpJdlVrcmorVG13Y2wyM2pWT0VwSDEvK054b09LTDhhCnJaNXhzMGtWejVzKzhxZTFJTVcxbkFlbTFGRVR5d0daM2k2d3JBZmZhdFd5TnJ3ZFdoK3lBK3NGaUxtZm5ZcW4KSzNCOXJCQUdVVmRlN2xDUXpwdUFWNUNTVXJBblEzb09vTGIreUhjSklYMnhaT1R4eVpEU0F0Qk0zYVl1U3F5Ywo0cDJhSStvd3prdy9Lc25JZmRQLzE2M2lvYkJOUU12YU5FdVJlUzNsUlNQdkpGaUQ5ZXB3ZW9VL0t1enRYOUdFCld5ZU9TRmwvSXdJREFRQUJvMmN3WlRBZEJnTlZIUTRFRmdRVUxoSkFLOSt2KzF3V09QaXBlR09veUFnblJTUXcKSHdZRFZSMGpCQmd3Rm9BVUxoSkFLOSt2KzF3V09QaXBlR09veUFnblJTUXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDTG1KUEs5WlkxCkN1enFlYWF1N1M2Q0N5M3NXOWVEanA2bjZ4ZlgrTzNwYThHSWNGV0FCRys3RXNOUDRmN2tjY0kyeEloOXh6TDIKVmd5QkdjYmdaZjJzY1VjZWkrSlJva3hLd0tVR2UzL2NMRzFaUjdnTW93WjdFZmxlcS80VnU4R1VEaXJUUzJjeQpRajRsL0ZxS2xlVW1jdHlWdTdmQmJ5dTg0TjI1UGNIUlVjVDJkT0hRNHQ2VVp1VXZMZ25DOGMvQUkzaGJGdlE3CkJrTHFEUHBQeDJYQkdRLzlNZGJlR1dySHVNNWlicXlvTEZtNFY2T1pxanpsWnU5V1YvT0ZtOUViVmliWEQ0MjgKVyt1TFBsVEFNRXNrY0c1SUJaWG9sQVZQYkladmlteHorTCthZVczbzlpZDRJWUFYZmlLMDdESmY3TGcvUnhNMApvak1QUU9xZWNSM1IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
