varReference:
- kind: Certificate
  path: spec/dnsNames
- kind: Certificate
  path: spec/issuerRef/name
- kind: Certificate
  path: spec/secretName 
- kind: Deployment
  path: spec/template/spec/volumes/secret/secretName 