apiVersion: v1
kind: Service
metadata:
  name: apiserver
  labels:
    api: kjournal
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    api: kjournal
    apiserver: "true"
