apiVersion: config.kjournal/v1alpha1
kind: APIServerConfig

backend:
  elasticsearch:
    url:
    - ${ELASTICSEARCH_URI}

apis:
- resource: containerlogs
  fieldMap:
    metadata.namespace: [kubernetes.namespace_name]
    metadata.creationTimestamp: ["@timestamp"]
    pod: [kubernetes.pod_name]
    container: [kubernetes.container_name]
    payload: ["."]
    metadata.labels: [kubernetes.labels]
    metadata.annotations.docker_id: [kubernetes.docker_id]
    metadata.annotations.host: [kubernetes.host]
    metadata.annotations.pod_id: [kubernetes.pod_id]

  dropFields:
  - payload.@timestamp
  - payload.kubernetes

  backend:
    elasticsearch:
      index: "*"
      timestampFields: ["@timestamp"]

- resource: events
  backend:
    elasticsearch:
      index: "*"
      timestampFields: ["metadata.creationTimestamp"]

- resource: auditevents
  backend:
    elasticsearch:
      index: "*"
      timestampFields: ["stageTimestamp"]

- resource: logs
  fieldMap:
    metadata.creationTimestamp: ["@timestamp", "metadata.creationTimestamp", "stageTimestamp"]
    payload: ["."]
  backend:
    elasticsearch:
      timestampFields: ["@timestamp", "metadata.creationTimestamp", "stageTimestamp"]
      index: "*"