name: docs

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: make mkdocs
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "gh-actions"
          git config pull.rebase true
          git pull origin gh-pages
          git checkout gh-pages index.yaml
          mv index.yaml docs/
      #- run: mkdocs gh-deploy --force