name: docs

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: make mkdocs
      - run: |
          git config pull.rebase true
          git pull origin gh-pages
      - run: mkdocs gh-deploy