name: pr-build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3
      - name: Setup Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 #v3.4.0
        with:
          go-version: 1.18.x
      - name: Restore Go cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 #v3.0.11
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: configs
        run: make configs -C cli
      - name: fmt
        run: make fmt -C cli
      - name: vet
        run: make vet -C cli
      - name: lint
        run: make lint -C cli
      - name: test
        run: make test -C cli
      - name: build
        run: make build -C cli
      - name: Send go coverage report
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cli/coverage.out
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run <make test configs> and commit changes'
            exit 1
          fi
      - name: Build container image
        run: |
          make docker-build -C cli BUILD_PLATFORMS=linux/amd64 \
            BUILD_ARGS="--cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max"
      - name: Create image tarball
        run: |
          docker save --output cli-container.tar kjournal/cli:latest
      - name: Upload container
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb #v3.1.1
        with:
          name: cli-container
          path: cli-container.tar        
      - name: Upload cli
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb #v3.1.1
        with:
          name: cli
          path: cli/bin/kjournal

  apiserver:
    runs-on: ubuntu-latest
    outputs:
      profiles: ${{ steps.profiles.outputs.matrix }}    
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3
      - name: Setup Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 #v3.4.0
        with:
          go-version: 1.18.x
      - name: Restore Go cache
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 #v3.0.11
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: configs
        run: make configs
      - name: fmt
        run: make fmt
      - name: vet
        run: make vet
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: Send go coverage report
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run <make test configs> and commit changes'
            exit 1
          fi
      - name: Build container image
        run: |
          make docker-build BUILD_PLATFORMS=linux/amd64 \
            BUILD_ARGS="--cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max"
      - name: Create image tarball
        run: |
          docker save --output apiserver-container.tar kjournal/apiserver:latest
      - name: Upload image
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb #v3.1.1
        with:
          name: apiserver-container
          path: apiserver-container.tar        
      - id: profiles
        name: Determine test profiles
        run: |
          profiles=$(ls config/tests | jq -R -s -c 'split("\n")[:-1]')
          echo $profiles
          echo "::set-output name=matrix::$profiles"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [apiserver,cli]
    strategy:
      matrix:
        profile: ${{ fromJson(needs.apiserver.outputs.profiles) }}
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b #v3
      - name: Setup Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 #v3.4.0
        with:
          go-version: 1.18.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 #v0.5.0
        with:
          name: kjournal
          version: v0.11.1
          image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
      - name: Download apiserver container
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 #v3.0.1
        with:
          name: apiserver-container
          path: /tmp
      - name: Download cli container
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 #v3.0.1
        with:
          name: cli-container
          path: /tmp
      - name: Download cli
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 #v3.0.1
        with:
          name: cli
          path: /tmp
      - name: Load images
        run: |
          docker load --input /tmp/apiserver-container.tar
          docker load --input /tmp/cli-container.tar
          docker image ls -a
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@6691bdeb1b0a3286fb7f70fd1423c10e81e5375f # v2.0.0
      - name: Deploy dependencies
        run: |
          kubectl create ns kjournal-system
          make kind-deploy-deps TEST_PROFILE=${{ matrix.profile }}
      - name: Deploy kjournal
        run: |
          chmod +x /tmp/kjournal
          /tmp/kjournal install --with-config-template=$(echo "${{ matrix.profile }}" | cut -d '_' -f 2)
      - name: Run validation tests
        run: |
          make kind-deploy-validate TEST_PROFILE=${{ matrix.profile }}
      - name: Debug failure
        if: failure()
        run: |
          echo "PODS ==================================="
          kubectl -n kjournal-system get pods -o wide
          echo "SVC ==================================="
          kubectl -n kjournal-system get svc -o wide
          echo "APISERVICE ==================================="
          kubectl get apiservice v1alpha1.core.kjournal
          echo "DESCRIBE ==================================="
          kubectl -n kjournal-system describe pods
          echo "CONTAINERLOGS ==================================="
          kubectl get containerlogs -n kjournal-system --field-selector payload.foobar=foobar -o json
      - name: Logs
        if: failure()
        run: |
          echo "APISERVER ==================================="
          kubectl -n kjournal-system logs deploy/kjournal-apiserver
          echo "VALIDATION ==================================="
          kubectl -n kjournal-system logs job/validation
          echo "FLUENTBIT ==================================="
          kubectl -n kjournal-system logs ds/fluent-bit
          echo "ELASTICSEARCH ==================================="
          kubectl -n kjournal-system logs sts/elasticsearch-master