name: rebase

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase') && (github.event.comment.author_association == 'CONTRIBUTOR' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3
        with:
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@6e572f08c244e2f04f9beb85a943eb618218714d #1.7
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
